server:
  port: 8090
spring:
  cloud:
    nacos: #如果不指定命名空间会默认注册到public里面去如果没有指定分组会注册到default_GROUP
      server-addr: 43.138.246.140:8848 #往这个地址注册
      username: nacos
      password: 9808
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#          filters:
#            - AddRequestHeader=cong,swag
#            - AddRequestParameter=name,666
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
        - id: cong-fallback
          uri: https://yupi.icu
          predicates:
            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
#        - - id: test2
#          uri: https://baidu.com
#          predicates:
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
dubbo:
  application:
    name: congapi-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-gateway
    address: nacos://43.138.246.140:8848